### ISSUE TITLE
eslint-mdx appears incompatible with remark-lint plugins that are esm-only

### ISSUE THREAD

**Issue by spaceninja** [mdx-js/eslint-mdx#338]
### Subject of the issue

I have a design system repo running Storybook MDX files. I followed their [linter-config](https://github.com/storybookjs/linter-config) example, which involves installing the MDX plugin for ESLint and a remark config running the recommended config.

I recently got a [Renovate PR to update remark-preset-lint to v6](https://github.com/MLTSHP/mltshp-patterns/pull/533).

The build fails on this PR, throwing the following lint error on every Storybook MDX file, which all start with a line like `import { Meta } from '@storybook/addon-docs/blocks';`:

> Parsing error: Must use import to load ES Module: /Users/scott/Sites/mltshp-patterns/node_modules/remark-preset-lint-recommended/index.js
require() of ES modules is not supported.
require() of /Users/scott/Sites/mltshp-patterns/node_modules/remark-preset-lint-recommended/index.js from /Users/scott/Sites/mltshp-patterns/node_modules/eslint-mdx/lib/processor.js is an ES module file as it is a .js file whose nearest parent package.json contains “type”: “module” which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove “type”: “module” from /Users/scott/Sites/mltshp-patterns/node_modules/remark-preset-lint-recommended/package.json.

I asked my buddy @calebeby for help, and he said:

> eslint-mdx is being used as commonjs (the package has both esm and commonjs versions). The commonjs version of eslint-mdx is trying to require() remark-preset-lint-recommended, which is [now only available as ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). You can’t require() an esm file.

> I looked at the ESM version of eslint-mdx and it is not valid (it is webpack-y esm, not standards esm) because it expects the require global to exist and uses it. So the problem will still exist even if you use the ESM version of eslint-mdx.

> You could file an issue on eslint-mdx to see if they have any ideas for importing remark packages that are esm-only. @wooorm maintains both so he will probably know if there is an answer
 
### Your environment

*   **OS**: Mac OS (and whatever 'nix variant Netlify is running)
*   **Packages**:
     * "eslint": "7.32.0",
     * "eslint-plugin-mdx": "1.15.0",
     * "remark-preset-lint-recommended": "6.0.1",
*   **Env**: Node LTS

Full config here: https://github.com/MLTSHP/mltshp-patterns

### Steps to reproduce

Follow the Storybook [linter-config](https://github.com/storybookjs/linter-config) example.

### Expected behaviour

I would expect to be able use remark-lint plugins that are esm-only with eslint-mdx

### Actual behaviour

I get an error complaining about `require()`.

**Comment by JounQin** [comment]
1. Native esm is not supported by ESLint yet
2. `eslint-mdx` is not compatible with latest `remark` (`remark-mdx@2`)

The first limitation may be fixed by refactored wrapping by `synckit` + `import()`, but it requires a lot of work, I'm not sure whether it is worth due to (2.

**Comment by lucasvazq** [comment]
For now, you can define a custom config file and run `remark-lint` through the terminal using that config.

```sh
yarn run remark **/*.mdx --no-stdout -r my_custom_remark_config.yml

# I combine the above command with this eslint plugin, so, the complete command that I execute is:
# yarn run eslint . --fix --ext .mdx && yarn run remark **/*.mdx --no-stdout -r my_custom_remark_config.yml
```

<details><summary><code>my_custom_remark_config.yml</code></summary><blockquote>

```yml
plugins:
  - - remark-lint-blockquote-indentation
    - 2
  - remark-lint-no-blockquote-without-marker
  - - remark-lint-checkbox-character-style
    - checked: x
      unchecked: " "
  - - remark-lint-code-block-style
    - fenced
  - - remark-lint-fenced-code-marker
    - "`"
  - remark-lint-fenced-code-flag
  - remark-lint-no-shortcut-reference-image
  - remark-lint-no-shortcut-reference-link
  - remark-lint-no-undefined-references
  - remark-lint-no-inline-padding
  - remark-lint-no-literal-urls
  - remark-lint-definition-case
  - remark-lint-definition-spacing
  - remark-lint-no-duplicate-definitions
  - remark-lint-no-unused-definitions
  - remark-lint-no-duplicate-headings
  - remark-lint-no-multiple-toplevel-headings
  - remark-lint-no-heading-content-indent
  - remark-lint-heading-increment
  - - remark-lint-heading-style
    - atx
  - - remark-lint-ordered-list-marker-style
    - "."
  - - remark-lint-unordered-list-marker-style
    - "-"
  - remark-lint-list-item-bullet-indent
  - remark-lint-list-item-content-indent
  - - remark-lint-list-item-indent
    - space
  - remark-lint-list-item-spacing
  - - remark-lint-emphasis-marker
    - "*"
  - - remark-lint-strong-marker
    - "*"
  - remark-lint-hard-break-spaces
  - remark-lint-no-consecutive-blank-lines
  - remark-lint-final-newline
```
</blockquote></details>

**:rotating_light: You can't use the [default config paths](https://www.npmjs.com/package/remark-cli#example-config-files-json-yaml-js) that remark uses.**
For example, you can't define the config that I set in `my_custom_remark_config.yml` in your `.remarkc.yml`.
Why? because `eslint-mdx` search for the remark config in that paths and throws the same error you are having right now when it try to load the plugins.
So, a workaround is to define a config file for `remark-lint` in another place and call it with `remark-cli`.
